spring.application.name=eureka-server
server.port=8761

# Este e o próprio servidor Eureka, então ele não deve
# se registrar nem buscar o registro de si.
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka

# Desativa o "self preservation" para facilitar o estudo em ambiente local
eureka.server.enable-self-preservation=false
